### ISSUE TITLE
Cannot resolve overloaded projection _≈_

### ISSUE THREAD

**Issue by Akshobhya1234** [Akshobhya1234/Agda-Algebra#6]
When defining direct product of quasigroup as 

> quasigroup : Quasigroup a ℓ₁ → Quasigroup b ℓ₂ → Quasigroup (a ⊔ b) (ℓ₁ ⊔ ℓ₂)
quasigroup M N = record
  { Carrier = M.Carrier × N.Carrier
  ; _≈_     = Pointwise {! M._≈_ !} {!  !}
  ; _∙_     = zip M._∙_ N._∙_
  ; _\\_    = zip M._\\_ N._\\_
  ; _//_    = zip M._//_ N._//_
  ; isQuasigroup = record
    { isEquivalence = ×-isEquivalence M.isEquivalence N.isEquivalence
    ; ∙-cong = zip M.∙-cong N.∙-cong
    ; \\-cong = zip M.\\-cong N.\\-cong
    ; //-cong = zip M.//-cong N.//-cong
    ; leftDivides = (λ x y → M.leftDividesˡ , N.leftDividesˡ <*> x <*> y) , (λ x y → M.leftDividesʳ , N.leftDividesʳ <*> x <*> y)
    ; rightDivides = (λ x y → M.rightDividesˡ , N.rightDividesˡ <*> x <*> y) , (λ x y → M.rightDividesʳ , N.rightDividesʳ <*> x <*> y)
    }
  } where module M = Quasigroup M; module N = Quasigroup N

It says "Cannot resolve overloaded projection _≈_ because it is not applied to a visible argument when inferring the type of M._≈_"

@JacquesCarette  Can you have a look at it.

**Comment by Akshobhya1234** [comment]
I think I found the issue. It depends on how the quasigroup is defined in stdlib. I will create an issue in stdlib to change the definition.

**Comment by JacquesCarette** [comment]
Have you tried `M._≈_` instead? That's the real name of the function.

**Comment by Akshobhya1234** [comment]
> Have you tried `M._≈_` instead? That's the real name of the function.

That is exactly the issue. We cannot use `M._≈_`.

**Comment by JacquesCarette** [comment]
But that makes no sense - that names comes from a module, and it shouldn't be overloaded at all. Can you provide a bigger explanation?

**Comment by JacquesCarette** [comment]
What I don't understand is how/where two version of `≈` as in-scope in `M`. I can understand that that's the problem.

**Comment by Akshobhya1234** [comment]
> What I don't understand is how/where two version of `≈` as in-scope in `M`. I can understand that that's the problem.

Got your question. To be honest even I am confused. The agda error will not make it clear as to where two version of `≈` is in-scope in `M`. (Could it be from `Magma`  that is defined in same file?) But I think we will face similar issue when we try to define direct product for `Lattice`.

**Comment by Akshobhya1234** [comment]
But for now this issue is resolved with the current changes proposed to quasigroup in stdlib.

**Comment by JacquesCarette** [comment]
One way to find out is to put `≈` in a hole, and do C-c C-w (for 'where', I think), and it will tell you where the definition(s) come from. (I think the documentation says "<W>hy in scope")

**Comment by Akshobhya1234** [comment]
@JacquesCarette  I got the issue. We had 2 instances of `_≈_`  one from Quasigroup and other from RawQuasigroup when we say 

`  open RawQuasigroup rawQuasigroup public`
`   using (_≈_; //-rawMagma; \\-rawMagma; ∙-rawMagma)`

in Quasigroup

To overcome this with we could remove `_≈_`  like  
   `  open RawQuasigroup rawQuasigroup public`
  `   using (//-rawMagma; \\-rawMagma; ∙-rawMagma)`

**Comment by JacquesCarette** [comment]
Yes, that's probably a good idea.
